version: "3.4"

services:
  php:
    build:
      context: .
    ports:
      - "8080:8000"
    volumes:
      - "./:/var/www/html:rw,cached"
      - "~/.composer/auth.json:/root/.composer/auth.json:ro"
