version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
    volumes:
      - "./:/var/www/html:rw,cached"
      - "~/.composer/auth.json:/root/.composer/auth.json:ro"

  http:
    image: nginx:1.19
    depends_on:
      - php
    volumes:
      - "./infrastructure/docker-full/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./public:/var/www/html/public:ro"
    ports:
      - "8080:80"
